# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArithCalc.ui'
#
# Created: Tue May 14 03:15:21 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 503)
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/App_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hundred_op = QtGui.QRadioButton(self.centralwidget)
        self.hundred_op.setGeometry(QtCore.QRect(650, 380, 71, 17))
        self.hundred_op.setAutoExclusive(False)
        self.hundred_op.setObjectName("hundred_op")
        self.hundre_ths_op = QtGui.QRadioButton(self.centralwidget)
        self.hundre_ths_op.setGeometry(QtCore.QRect(580, 420, 82, 17))
        self.hundre_ths_op.setAutoExclusive(False)
        self.hundre_ths_op.setObjectName("hundre_ths_op")
        self.tens_option = QtGui.QRadioButton(self.centralwidget)
        self.tens_option.setGeometry(QtCore.QRect(580, 380, 51, 17))
        self.tens_option.setAutoExclusive(False)
        self.tens_option.setObjectName("tens_option")
        self.ones_option = QtGui.QRadioButton(self.centralwidget)
        self.ones_option.setGeometry(QtCore.QRect(500, 380, 61, 17))
        self.ones_option.setAutoExclusive(False)
        self.ones_option.setObjectName("ones_option")
        self.ten_ths_option = QtGui.QRadioButton(self.centralwidget)
        self.ten_ths_option.setGeometry(QtCore.QRect(500, 420, 51, 17))
        self.ten_ths_option.setAutoExclusive(False)
        self.ten_ths_option.setObjectName("ten_ths_option")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 40, 391, 421))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bottom_lineEdit = QtGui.QLineEdit(self.frame)
        self.bottom_lineEdit.setGeometry(QtCore.QRect(90, 100, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(48)
        font.setWeight(75)
        font.setBold(True)
        self.bottom_lineEdit.setFont(font)
        self.bottom_lineEdit.setMouseTracking(False)
        self.bottom_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottom_lineEdit.setAcceptDrops(False)
        self.bottom_lineEdit.setObjectName("bottom_lineEdit")
        self.top_lineEdit = QtGui.QLineEdit(self.frame)
        self.top_lineEdit.setGeometry(QtCore.QRect(90, 10, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(48)
        font.setWeight(75)
        font.setBold(True)
        self.top_lineEdit.setFont(font)
        self.top_lineEdit.setMouseTracking(False)
        self.top_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.top_lineEdit.setAcceptDrops(False)
        self.top_lineEdit.setText("")
        self.top_lineEdit.setObjectName("top_lineEdit")
        self.answer_lineEdit = QtGui.QLineEdit(self.frame)
        self.answer_lineEdit.setGeometry(QtCore.QRect(90, 220, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(48)
        font.setWeight(75)
        font.setBold(True)
        self.answer_lineEdit.setFont(font)
        self.answer_lineEdit.setMouseTracking(False)
        self.answer_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.answer_lineEdit.setAcceptDrops(False)
        self.answer_lineEdit.setObjectName("answer_lineEdit")
        self.start_button = QtGui.QToolButton(self.frame)
        self.start_button.setGeometry(QtCore.QRect(90, 370, 111, 51))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtGui.QToolButton(self.frame)
        self.stop_button.setGeometry(QtCore.QRect(270, 370, 111, 51))
        self.stop_button.setObjectName("stop_button")
        self.operator_displ = QtGui.QLabel(self.frame)
        self.operator_displ.setGeometry(QtCore.QRect(10, 100, 71, 80))
        self.operator_displ.setText("")
        self.operator_displ.setPixmap(QtGui.QPixmap(":/icons/Orange.png"))
        self.operator_displ.setObjectName("operator_displ")
        self.pause_button = QtGui.QToolButton(self.frame)
        self.pause_button.setGeometry(QtCore.QRect(90, 310, 291, 51))
        self.pause_button.setObjectName("pause_button")
        self.plus_op = QtGui.QRadioButton(self.centralwidget)
        self.plus_op.setGeometry(QtCore.QRect(500, 170, 109, 17))
        self.plus_op.setAutoExclusive(False)
        self.plus_op.setObjectName("plus_op")
        self.div_op = QtGui.QRadioButton(self.centralwidget)
        self.div_op.setGeometry(QtCore.QRect(500, 130, 109, 17))
        self.div_op.setAutoExclusive(False)
        self.div_op.setObjectName("div_op")
        self.format_converter = QtGui.QRadioButton(self.centralwidget)
        self.format_converter.setGeometry(QtCore.QRect(500, 50, 109, 17))
        self.format_converter.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.format_converter.setAutoExclusive(False)
        self.format_converter.setObjectName("format_converter")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(680, 40, 120, 311))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.mult_option = QtGui.QRadioButton(self.centralwidget)
        self.mult_option.setGeometry(QtCore.QRect(500, 90, 109, 17))
        self.mult_option.setAutoExclusive(False)
        self.mult_option.setObjectName("mult_option")
        self.subtr_op = QtGui.QRadioButton(self.centralwidget)
        self.subtr_op.setGeometry(QtCore.QRect(500, 210, 109, 17))
        self.subtr_op.setAutoExclusive(False)
        self.subtr_op.setObjectName("subtr_op")
        self.consec_op = QtGui.QRadioButton(self.centralwidget)
        self.consec_op.setGeometry(QtCore.QRect(500, 250, 109, 17))
        self.consec_op.setAutoExclusive(False)
        self.consec_op.setObjectName("consec_op")
        self.rand_op = QtGui.QRadioButton(self.centralwidget)
        self.rand_op.setGeometry(QtCore.QRect(500, 290, 109, 17))
        self.rand_op.setAutoExclusive(False)
        self.rand_op.setObjectName("rand_op")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSession = QtGui.QMenu(self.menubar)
        self.menuSession.setObjectName("menuSession")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew_2 = QtGui.QAction(MainWindow)
        self.actionNew_2.setObjectName("actionNew_2")
        self.actionDelete_Student = QtGui.QAction(MainWindow)
        self.actionDelete_Student.setObjectName("actionDelete_Student")
        self.actionView_Stats = QtGui.QAction(MainWindow)
        self.actionView_Stats.setObjectName("actionView_Stats")
        self.actionLog_in = QtGui.QAction(MainWindow)
        self.actionLog_in.setObjectName("actionLog_in")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSession.addAction(self.actionLog_in)
        self.menuSession.addAction(self.actionNew_2)
        self.menuSession.addAction(self.actionDelete_Student)
        self.menuSession.addSeparator()
        self.menuSession.addAction(self.actionView_Stats)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSession.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.start_button, self.stop_button)
        MainWindow.setTabOrder(self.stop_button, self.format_converter)
        MainWindow.setTabOrder(self.format_converter, self.div_op)
        MainWindow.setTabOrder(self.div_op, self.plus_op)
        MainWindow.setTabOrder(self.plus_op, self.ones_option)
        MainWindow.setTabOrder(self.ones_option, self.tens_option)
        MainWindow.setTabOrder(self.tens_option, self.hundred_op)
        MainWindow.setTabOrder(self.hundred_op, self.ten_ths_option)
        MainWindow.setTabOrder(self.ten_ths_option, self.hundre_ths_op)
        MainWindow.setTabOrder(self.hundre_ths_op, self.top_lineEdit)
        MainWindow.setTabOrder(self.top_lineEdit, self.bottom_lineEdit)
        MainWindow.setTabOrder(self.bottom_lineEdit, self.answer_lineEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.hundred_op.setText(QtGui.QApplication.translate("MainWindow", "Hundreds", None, QtGui.QApplication.UnicodeUTF8))
        self.hundre_ths_op.setText(QtGui.QApplication.translate("MainWindow", "Hundreths", None, QtGui.QApplication.UnicodeUTF8))
        self.tens_option.setText(QtGui.QApplication.translate("MainWindow", "Tens", None, QtGui.QApplication.UnicodeUTF8))
        self.ones_option.setText(QtGui.QApplication.translate("MainWindow", "Ones", None, QtGui.QApplication.UnicodeUTF8))
        self.ten_ths_option.setText(QtGui.QApplication.translate("MainWindow", "Tenths", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("MainWindow", "Start Session", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("MainWindow", "Stop Session", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_button.setText(QtGui.QApplication.translate("MainWindow", "Pause Session", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_op.setText(QtGui.QApplication.translate("MainWindow", "Addition", None, QtGui.QApplication.UnicodeUTF8))
        self.div_op.setText(QtGui.QApplication.translate("MainWindow", "Division", None, QtGui.QApplication.UnicodeUTF8))
        self.format_converter.setText(QtGui.QApplication.translate("MainWindow", "Format Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.mult_option.setText(QtGui.QApplication.translate("MainWindow", "Multiplication", None, QtGui.QApplication.UnicodeUTF8))
        self.subtr_op.setText(QtGui.QApplication.translate("MainWindow", "Subtraction", None, QtGui.QApplication.UnicodeUTF8))
        self.consec_op.setText(QtGui.QApplication.translate("MainWindow", "Consecutive", None, QtGui.QApplication.UnicodeUTF8))
        self.rand_op.setText(QtGui.QApplication.translate("MainWindow", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSession.setTitle(QtGui.QApplication.translate("MainWindow", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_2.setText(QtGui.QApplication.translate("MainWindow", "New Student", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Student.setText(QtGui.QApplication.translate("MainWindow", "Delete Student", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Stats.setText(QtGui.QApplication.translate("MainWindow", "View Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog_in.setText(QtGui.QApplication.translate("MainWindow", "Log-in", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
